import type { NextPage } from "next";
import Head from "next/head";
import Header from "../src/components/Header";
import { Main } from "../src/components/Main";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Vetores Paralelos e Ortogonais</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
    </div>
  );
};

export default Home;
