import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Title } from "../Main/Style";
import * as S from "./style";

const Index = () => {
  return (
    <div>
      <Head>
        <title>Vetores Paralelos e Ortogonais</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.index>
        <div>
          <Title>
            Verificador de Paralelismo e Ortogonalidade entre vetores
          </Title>
          <p>
            Vetores são paralelos quando a divisão de suas cordenadas são iguais.
          </p>
          <p>
            Vetores são ortogonais quando o produto escalar entre eles é igual a 0 (zero).
          </p>
          <Link href={"/main"}>
            <button>COMEÇAR</button>
          </Link>
        </div>
        <img src="/mainimage.png" alt="mainimage" />
      </S.index>
    </div>
  );
};

export default Index;
